### ISSUE TITLE
Strange Download Stats

### ISSUE THREAD

**Issue by HereIsKevin** [0x44RU5H/ashmail#2]
5.3k downloads a month? Are you sure? Could you explain? Seems strange to me...

**Comment by 0x44RU5H** [comment]
This package was released about 2 to 3 weeks ago, so the statistic is not an average. As for the amount, it was due to some posts on social media platforms and collaborations with other developers. The badge is sourced from sheilds.io, which I would argue is a reputable source.

**Comment by HereIsKevin** [comment]
On the other hand, it is very unusual for a package with only 1 star to have 5.3k downloads a month...

**Comment by HereIsKevin** [comment]
[PyPI Download Stats](https://pypistats.org/packages/ashmail) seems to say that most of the downloads come from Python 3.8 on Linux.

**Comment by HereIsKevin** [comment]
@0x44RU5H Where did you post on social media? I can't seem to find anything on Reddit or Hacker News.

**Comment by 0x44RU5H** [comment]
> On the other hand, it is very unusual for a package with only 1 star to have 5.3k downloads a month...

I advertised the package and not the github repository.

**Comment by 0x44RU5H** [comment]
> [PyPI Download Stats](https://pypistats.org/packages/ashmail) seems to say that most of the downloads come from Python 3.8 on Linux.

Most of the users are running AWS or GCP servers.

**Comment by 0x44RU5H** [comment]
> @0x44RU5H Where did you post on social media? I can't seem to find anything on Reddit or Hacker News.

By social media, I meant Discord. I spread the word on Discord and also asked server owners to advertise the package to their members.

**Comment by HereIsKevin** [comment]
From the stats, it seems that the downloads per day suddenly zooms up to 4.6k on 5/18, then immediately drops to about 30...

**Comment by 0x44RU5H** [comment]
Based on the previously given information, I think it is pretty clear why that happened...
